### ISSUE TITLE
Error when adding grid start

### ISSUE THREAD

**Issue by planepix** [Web-Ex-Machina/contao-grid#1]
Hello,
i tried the latest realease in an 4.6.14 installation and get this error when adding CE grid-start:

`syntax error, unexpected ')'`

Log entry:
`[2019-07-08 14:41:52] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "syntax error, unexpected ')'" at /www/htdocs/xxx/vendor/webexmachina/contao-grid/src/Widgets/GridElementWizard.php line 119 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): syntax error, unexpected ')' at /www/htdocs/xxx/vendor/webexmachina/contao-grid/src/Widgets/GridElementWizard.php:119)"} []`

**Comment by LupusVII** [comment]
Hello !
Thanks for your input, I've made a 0.3.3 release with some bugfixes. I could not reproduce your issue though so if the new release don't fix it, can you post me the version of PHP you are using please ?

Also, the "CSS Grid" might be a little hard to understand because we are using a CSS framework with it. It's not really implemented yet but it will be a standalone one day. (The BS4 grid works well though).

**Comment by planepix** [comment]
Hi LupusVII,
thank you for your response and update.
Update works well under PHP 7.2.

So i will have an eye on the development when frameworks are implemented :).

First thought was: Great CSS Gris with a bundle.
Keep on work and thank you for your efforts for contao!

Regards, Thomas

**Comment by LupusVII** [comment]
Stay tuned, there is a lot of improvements incoming for this module ;)
Thanks for your feedback !
Regards,
Julien
